import '../models/food_item.dart';

class DummyFoodRepo {
  static List<FoodItem> getFoodItems() {
    return [
      FoodItem(
        id: '1',
        title: 'Vegetable Biryani',
        category: 'Cooked Meals',
        images: ['assets/images/r1.jpeg'],
        quantity: '200',
        expiry: 'Tomorrow 1pm',
        pickupTime: '9:00 PM',
        location: 'Moulali',
        latitude: 17.4399,
        longitude: 78.4983,
        phone: '9876543210',
        notes:
            'Freshly prepared vegetable biryani. Please collect within time.',
      ),
      FoodItem(
        id: '2',
        title: 'Chapati',
        category: 'Cooked Meals',
        images: ['assets/images/r2.jpeg'],
        quantity: '450',
        expiry: 'Today',
        pickupTime: 'Today 3pm',
        location: 'City Center',
        latitude: 17.4440,
        longitude: 78.4820,
        phone: '9876543211',
        notes: 'Soft chapatis packed in boxes.',
      ),
      FoodItem(
        id: '3',
        title: 'Snacks Mix',
        category: 'Snacks',
        images: ['assets/images/r3.jpeg'],
        quantity: '100',
        expiry: '26-03-26',
        pickupTime: '7:30 PM',
        location: 'City Center',
        latitude: 17.4435,
        longitude: 78.4808,
        phone: '9876543212',
        notes: 'Assorted snack mix, suitable for distribution.',
      ),
      FoodItem(
        id: '4',
        title: 'Veg Puffs',
        category: 'Bakery',
        images: ['assets/images/r4.jpeg'],
        quantity: '4',
        expiry: 'Today',
        pickupTime: '6:30 PM',
        location: 'City Center',
        latitude: 17.4421,
        longitude: 78.4799,
        phone: '9876543213',
        notes: 'Freshly baked veg puffs.',
      ),
      FoodItem(
        id: '5',
        title: 'Evening Snacks',
        category: 'Snacks',
        images: ['assets/images/r5.jpeg'],
        quantity: '3',
        expiry: 'Today',
        pickupTime: '5:30 PM',
        location: 'City Center',
        latitude: 17.4415,
        longitude: 78.4812,
        phone: '9876543214',
        notes: 'Evening snack combo pack.',
      ),
    ];
  }
}
